CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    EMAIL VARCHAR(45),
    FIRST_NAME VARCHAR(45),
    LAST_NAME VARCHAR(45)
);

CREATE TABLE SERVICE (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    SERVICE_NAME VARCHAR(45),
    SERVICE_GROUP VARCHAR(45),
    SERVICE_PRICE DECIMAL(15,2),
    SERVICE_TYPE VARCHAR(45),
    CLASS_DURATION INT
);

CREATE TABLE CUSTOMER_CLASS (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    CUSTOMER_ID INT,
    CLASS_ID INT
);